# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'study1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for study1
  pod 'Texture', '~> 2.5.1'
  pod 'SnapKit', '~> 4.0.0'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
  pod 'KMCGeigerCounter'
  
  pod 'DLNCore', :git => 'https://github.com/dklinzh/DLNCore.git'
  pod 'DLNFoundation', :git => 'https://github.com/dklinzh/DLNFoundation.git'
  pod 'NodeExtension', :git => 'https://github.com/dklinzh/NodeExtension.git', :branch => 'objc'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  
  pod 'SkeletonView', '~> 1.0.4'
end
